### Mengambil Semua Catatan
GET https://tcc-tugas3-backend-361164671321.us-central1.run.app/api/notes
Accept: application/json

### Menambah Catatan Baru
POST https://tcc-tugas3-backend-361164671321.us-central1.run.app/api/notes
Content-Type: application/json

{
    "judul": "Tugas 2 Praktikum TCC",
    "isi": "Mengerjakan tugas 2 Praktikum TCC (Belum Selesai)."
}

### Mengubah Catatan (Ganti :id dengan ID asli dari database)
PUT https://tcc-tugas3-backend-361164671321.us-central1.run.app/api/notes/1
Content-Type: application/json

{
    "judul": "Tugas 2 Praktikum TCC (Updated)",
    "isi": "Tugas 2 Praktikum TCC (Sudah Selesai)."
}

### Menghapus Catatan (Ganti :id dengan ID asli)
DELETE https://tcc-tugas3-backend-361164671321.us-central1.run.app/api/notes/1